services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile

    container_name: backend

    ports:
      - "5001:5001"

    volumes:
      - ./Backend:/app

    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile

    container_name: frontend

    restart: "no"

    depends_on:
      - backend